name: Continuous Delivery

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  GORELEASER_VERSION: v1.22.2

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unshallow repo
        run: git fetch --prune --unshallow --tags -f

      - name: Setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}' > .release-env

      - name: GoReleaser publish
        run: |-
          docker run \
            --rm \
            -e CGO_ENABLED=1 \
            --env-file .release-env \
            -v `pwd`:/src \
            -w /src \
            ghcr.io/goreleaser/goreleaser-cross:${{ env.GORELEASER_VERSION }} \
            release --clean
