name: Continuous Delivery

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  GORELEASER_VERSION: v1.22.3
  UPX_VERSION: 4.2.4

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UPX
        run: |
          cd /tmp
          F="upx-${UPX_VERSION}-amd64_linux"
          curl -OL "https://github.com/upx/upx/releases/download/v${UPX_VERSION}/${F}.tar.xz"
          tar xf "${F}.tar.xz"
          mv "${F}/upx" /usr/local/bin/
          upx --version

      - name: Unshallow repo
        run: git fetch --prune --unshallow --tags -f

      - name: Setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}' > .release-env

      - name: GoReleaser publish
        run: |-
          docker run \
            --rm \
            -e CGO_ENABLED=1 \
            --env-file .release-env \
            -v `pwd`:/src \
            -v /usr/local/bin/upx:/usr/local/bin/upx \
            -w /src \
            ghcr.io/goreleaser/goreleaser-cross:${{ env.GORELEASER_VERSION }} \
            release --clean
